name: fed3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - scipy=1.7.3
  - faiss-gpu
  - tqdm
  - pip:
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - gaussian-splatting/submodules/simple-knn
    - git+https://github.com/NVlabs/tiny-cuda-nn/@v1.6#subdirectory=bindings/torch
